---
name: Pull Request

on:
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  test-scripts:
    name: Test scripts
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Custom Data updated test
        run: make cga-proxy-custom-data git-clean
