---
name: Pull Request

on:
  pull_request:

defaults:
  run:
    shell: bash

jobs:

  cga-proxy-test:
    name: CGA Proxy Test
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Custom Data updated test
        run: |
          make cga-proxy-custom-data git-clean
